export enum PostStatus {
  POSTED = 'POSTED',
  TO_BE_APPROVED = 'TO_BE_APPROVED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REPORTED = 'REPORTED',
  IN_REVIEW = 'IN_REVIEW',
  REPORT_ACCEPTED = 'REPORT_ACCEPTED',
  REPORT_REJECTED = 'REPORT_REJECTED',
}
